[project]
name = "mojo-secp256k1"
version = "0.1.0"
description = "Deterministic secp256k1 signing primitives in Mojo"
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]

platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = "*"
pip = "*"
mojo = "*"

[pypi-dependencies]
eth-keys = "*"

[tasks.test]
cmd = "mojo -I decimojo/src -I keccak test_secp256k1.mojo"

[tasks.kat]
cmd = "python python_tests/kat_and_benchmark.py"

[tasks.test-kat]
cmd = "mojo -I decimojo/src test_secp256k1_kat.mojo"

