[workspace]
name = "mojo-secp256k1"
version = "0.1.0"
description = "Deterministic secp256k1 signing primitives in Mojo"
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]

platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = "*"
pip = "*"
mojo = "*"

[pypi-dependencies]
eth-keys = "*"
eth-hash = {version = "*", extras = ["pycryptodome"]}
pycryptodome = "*"

# Main test tasks that run everything
[tasks.test]
cmd = ".pixi/envs/default/bin/python python_tests/run_all.py"

[tasks.ci]
cmd = ".pixi/envs/default/bin/python python_tests/run_all.py"

# Individual component tests for development
[tasks.test-core]
cmd = "mojo -I decimojo/src -I keccak test_secp256k1.mojo"

[tasks.test-kat]
cmd = "mojo -I decimojo/src test_secp256k1_kat.mojo"

[tasks.test-rfc6979]
cmd = "mojo -I . -I decimojo/src -I keccak test_seckp256k1_rfc6979.mojo"

[tasks.test-recover]
cmd = "mojo -I . -I decimojo/src -I keccak test_ecdsa_recover.mojo"

# Cross-verification with eth-keys
[tasks.verify-signatures]
cmd = 'bash -lc "mojo -I . -I decimojo/src -I keccak test_sign_dump.mojo | .pixi/envs/default/bin/python python_tests/verify_eth_keys.py"'

[tasks.verify-recover]
cmd = 'bash -lc "mojo -I . -I decimojo/src -I keccak test_recover_dump.mojo | .pixi/envs/default/bin/python python_tests/recover_and_compare.py"'

# Additional tests and benchmarks
[tasks.run-kat]
cmd = ".pixi/envs/default/bin/python python_tests/kat_and_benchmark.py"

[tasks.verify-all]
cmd = ".pixi/envs/default/bin/python python_tests/verify_signatures.py"
